language: php

php:
  # using major version aliases

  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent hhvm version
  - hhvm

# optionally set up exclusions and allowed failures in the matrix
matrix:
  exclude:
    - php: hhvm

install:
  - composer install

script: ./vendor/bin/phpunit --configuration phpunit.xml